apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
  namespace: default
spec:
  type: pubsub.azure.servicebus
  metadata:
  - name: connectionString
    secretKeyRef:
      name: sbConnectionString
auth:
    secretStore: azurekeyvault